import type { NbtCompound, NbtList, NbtTag } from './Nbt';
const IDS: Record<NbtTag['type'],number>={byte:1,short:2,int:3,long:4,float:5,double:6,byteArray:7,string:8,list:9,compound:10,intArray:11}; const TYPES: Record<number,NbtTag['type']>={1:'byte',2:'short',3:'int',4:'long',5:'float',6:'double',7:'byteArray',8:'string',9:'list',10:'compound',11:'intArray'};
const MAX=16*1024*1024,DEPTH=64; class Writer { private chunks:number[]=[]; public byte(v:number){this.chunks.push(v&255)} public i16(v:number){this.byte(v>>8);this.byte(v)} public i32(v:number){this.byte(v>>24);this.byte(v>>16);this.byte(v>>8);this.byte(v)} public bytes(v:Uint8Array){for(const x of v)this.byte(x)} public out(){return Uint8Array.from(this.chunks)} }
class Reader { public p=0; public constructor(private readonly b:Uint8Array){} byte(){if(this.p>=this.b.length)throw new Error('Truncated NBT');return this.b[this.p++]!} i16(){return (this.byte()<<8)|this.byte()} i32(){return (this.byte()<<24)|(this.byte()<<16)|(this.byte()<<8)|this.byte()} bytes(n:number){if(n<0||n>MAX||this.p+n>this.b.length)throw new Error('Invalid NBT length');const v=this.b.slice(this.p,this.p+n);this.p+=n;return v} }
const text=new TextEncoder(), decode=new TextDecoder(); const finite=(n:number)=>{if(!Number.isFinite(n))throw new Error('Non-finite NBT number');return n};
function writeName(w:Writer,s:string){const b=text.encode(s);if(b.length>65535)throw new Error('NBT name too long');w.i16(b.length);w.bytes(b)} function readName(r:Reader){return decode.decode(r.bytes(r.i16()))}
function payload(w:Writer,t:NbtTag,d:number){if(d>DEPTH)throw new Error('NBT nesting too deep');switch(t.type){case'byte':w.byte(t.value);break;case'short':w.i16(t.value);break;case'int':w.i32(t.value);break;case'long':{const v=BigInt.asIntN(64,t.value);for(let i=7n;i>=0n;i--)w.byte(Number((v>>(i*8n))&255n));break}case'float':case'double':{const n=finite(t.value), a=new ArrayBuffer(t.type==='float'?4:8),v=new DataView(a);t.type==='float'?v.setFloat32(0,n,false):v.setFloat64(0,n,false);w.bytes(new Uint8Array(a));break}case'byteArray':w.i32(t.value.length);w.bytes(t.value);break;case'string':writeName(w,t.value);break;case'intArray':w.i32(t.value.length);for(const n of t.value)w.i32(n);break;case'list':w.byte(IDS[t.elementType]);w.i32(t.value.length);for(const x of t.value){if(x.type!==t.elementType)throw new Error('NBT list element type mismatch');payload(w,x,d+1)}break;case'compound':for(const [k,v] of t.value){w.byte(IDS[v.type]);writeName(w,k);payload(w,v,d+1)}w.byte(0);break}}
function readPayload(r:Reader,type:NbtTag['type'],d:number):NbtTag{if(d>DEPTH)throw new Error('NBT nesting too deep');switch(type){case'byte':return{type,value:(r.byte()<<24)>>24};case'short':return{type,value:(r.i16()<<16)>>16};case'int':return{type,value:r.i32()};case'long':{let v=0n;for(let i=0;i<8;i++)v=(v<<8n)|BigInt(r.byte());return{type,value:BigInt.asIntN(64,v)}}case'float':return{type,value:new DataView(r.bytes(4).buffer).getFloat32(0,false)};case'double':return{type,value:new DataView(r.bytes(8).buffer).getFloat64(0,false)};case'byteArray':return{type,value:r.bytes(r.i32())};case'string':return{type,value:readName(r)};case'intArray':{const n=r.i32();if(n<0||n>MAX/4)throw new Error('Invalid NBT int array');const a=new Int32Array(n);for(let i=0;i<n;i++)a[i]=r.i32();return{type,value:a}}case'list':{const id=r.byte(),elementType=TYPES[id];if(elementType===undefined)throw new Error('Invalid NBT list type');const n=r.i32();if(n<0||n>MAX)throw new Error('Invalid NBT list length');const value:NbtTag[]=[];for(let i=0;i<n;i++)value.push(readPayload(r,elementType,d+1));return{type,elementType,value} as NbtList}case'compound':{const value=new Map<string,NbtTag>();for(;;){const id=r.byte();if(id===0)break;const child=TYPES[id];if(child===undefined)throw new Error('Invalid NBT tag type');value.set(readName(r),readPayload(r,child,d+1));}return{type,value} as NbtCompound}}}
export function encodeNbt(root:NbtCompound,name=''):Uint8Array{const w=new Writer();w.byte(10);writeName(w,name);payload(w,root,0);return w.out()} export function decodeNbt(bytes:Uint8Array):{readonly name:string;readonly root:NbtCompound}{if(bytes.length>MAX)throw new Error('NBT payload too large');const r=new Reader(bytes);if(r.byte()!==10)throw new Error('NBT root must be compound');const result={name:readName(r),root:readPayload(r,'compound',0) as NbtCompound};if(r.p!==bytes.length)throw new Error('Trailing NBT data');return result}
