import type { BlockId } from '../blocks/BlockId';import { BlockIds } from '../blocks/BlockId';import type { BlockRegistry } from '../blocks/BlockRegistry';import type { Player } from './Player';import type { ChunkManager } from '../world/ChunkManager';import type { BlockUpdateWorld } from '../world/BlockUpdateWorld';import type { RaycastHit } from '../world/Raycaster';import type { ItemEntityManager } from '../entities/items/ItemEntityManager';import { resolveBlockDrops } from '../entities/items/BlockDropResolver';import { Inventory } from '../inventory/Inventory';import { calculateMining } from '../mining/MiningRules';import { blockBreakDurabilityCost } from '../items/ItemDurability';
/** Frame input capture + authoritative 20 Hz mining progress owner. */
export class BreakingController{private miningBlockPos:{x:number;y:number;z:number}|undefined;private progress=0;private blockHitWait=0;private capturedHit:RaycastHit|undefined;private capturedHeld=false;private expectedBlock:BlockId=BlockIds.Air;private heldKey='';private canHarvest=true;private onBlockBrokenHandler?: (blockId:number,x:number,y:number,z:number)=>void;
 public constructor(private readonly player:Player,private readonly chunkManager:ChunkManager,private readonly blockRegistry:BlockRegistry,private readonly world:BlockUpdateWorld,private readonly items:ItemEntityManager,private readonly inventory:Inventory=new Inventory(),private readonly selectedSlot:()=>number=()=>0){}
 public setOnBlockBrokenHandler(handler:(blockId:number,x:number,y:number,z:number)=>void):void{this.onBlockBrokenHandler=handler;}public getMiningBlockPos(){return this.miningBlockPos;}public getProgress():number{return this.progress;}private clearState(animation:'cancel'|'recover'|'preserve'):void{this.miningBlockPos=undefined;this.progress=0;this.capturedHit=undefined;this.expectedBlock=BlockIds.Air;this.heldKey='';if(animation==='cancel')this.player.stopBreakingAnimation();else if(animation==='recover')this.player.finishBreakingAnimation();}public reset():void{this.clearState('cancel');}
 public update(currentHit:RaycastHit|undefined,isLeftClickHeld:boolean,_deltaSeconds:number):void{this.capture(currentHit,isLeftClickHeld);}
 public capture(currentHit:RaycastHit|undefined,isHeld:boolean):void{this.capturedHeld=isHeld;if(!isHeld||!currentHit||!this.player.isAlive()||this.player.isEating||currentHit.blockDefinition.isBreakable===false){if(this.blockHitWait>0)this.clearState('preserve');else this.reset();return;}const {x,y,z}=currentHit.blockPos,stack=this.inventory.getStack(this.selectedSlot()),key=stack?`${stack.identity.type}:${stack.identity.id}:${stack.metadata}:${stack.damage}`:'hand',changed=!this.miningBlockPos||this.miningBlockPos.x!==x||this.miningBlockPos.y!==y||this.miningBlockPos.z!==z;if(changed){this.progress=0;this.miningBlockPos={x,y,z};this.expectedBlock=this.world.getBlock(x,y,z);this.heldKey=key;if(this.blockHitWait===0)this.player.beginBreakingAnimation(true);}else if(this.heldKey!==key){this.progress=0;this.heldKey=key;if(this.blockHitWait===0)this.player.beginBreakingAnimation(true);}else if(this.blockHitWait===0)this.player.beginBreakingAnimation();this.capturedHit=currentHit;}
 public tick():void{if(this.blockHitWait>0){this.blockHitWait--;this.progress=0;return;}if(!this.capturedHeld||!this.capturedHit||!this.miningBlockPos||!this.player.isAlive()||this.player.isEating){this.reset();return;}const {x,y,z}=this.miningBlockPos,blockId=this.world.getBlock(x,y,z),definition=this.blockRegistry.getById(blockId);if(blockId!==this.expectedBlock||blockId===BlockIds.Air||!definition||definition.isBreakable===false){this.reset();return;}const stack=this.inventory.getStack(this.selectedSlot()),key=stack?`${stack.identity.type}:${stack.identity.id}:${stack.metadata}:${stack.damage}`:'hand';if(key!==this.heldKey){this.progress=0;this.heldKey=key;return;}const result=calculateMining({block:definition,held:stack,underwater:this.player.headUnderwater,grounded:this.player.grounded});this.canHarvest=result.canHarvest;if(result.unbreakable){this.progress=0;return;}this.progress=result.instant?1:this.progress+result.progressPerTick;if(this.progress>=.9999){this.breakBlock(x,y,z,this.canHarvest);this.clearState('recover');this.blockHitWait=5;}}
 private breakBlock(x:number,y:number,z:number,canHarvest:boolean):void{if(!this.chunkManager.getChunk(Math.floor(x/16),Math.floor(z/16)))return;const id=this.world.getBlock(x,y,z),metadata=this.world.getBlockMetadata(x,y,z);if(!this.world.setBlock(x,y,z,BlockIds.Air,{reason:'player',notifyNeighbours:true,updateLighting:true}))return;this.onBlockBrokenHandler?.(id,x,y,z);for(const drop of resolveBlockDrops(id,metadata,canHarvest))this.items.spawnItem(x+.5,y+.2,z+.5,drop,10);const slot=this.selectedSlot(),cost=blockBreakDurabilityCost(this.inventory.getStack(slot));if(cost>0&&this.inventory.damageItemInSlot(slot,cost)?.status==='broken')this.items.emitItemBreak(this.player.position.x,this.player.position.y,this.player.position.z);}
}
