import type { HotbarLayout } from '../inventory/HotbarLayout';import type { Player } from './Player';
export type HeartState='empty'|'half'|'full'|'halfDamage'|'fullDamage';
/** Explicit sprite state for each of ten hearts. Damage phase shows recent pre-hit health. */
export function getHeartStates(health:number,recentHealth=health,damagePhase=false):HeartState[]{const current=Math.max(0,Math.min(20,Math.floor(health))),recent=Math.max(current,Math.min(20,Math.floor(recentHealth))),display=damagePhase?recent:current;return Array.from({length:10},(_,index)=>{const units=display-index*2;if(units>=2)return damagePhase?'fullDamage':'full';if(units===1)return damagePhase?'halfDamage':'half';return'empty';});}
const TEXTURE:Readonly<Record<Exclude<HeartState,'empty'>,string>>={full:'/textures/gui/heart_full.png',half:'/textures/gui/heart_half.png',fullDamage:'/textures/gui/heart_full_damage.png',halfDamage:'/textures/gui/heart_half_damage.png'};
export class HealthHudRenderer{private readonly root=typeof document!=='undefined'?document.createElement('div'):({} as HTMLDivElement);private readonly fills:HTMLImageElement[]=[];
 public constructor(private readonly player:Player){if(typeof document==='undefined')return;this.root.id='health-hud';this.root.style.cssText='position:fixed;pointer-events:none;z-index:120;image-rendering:pixelated';for(let i=0;i<10;i++){const slot=document.createElement('div');slot.style.cssText="position:absolute;width:9px;height:9px;background:url('/textures/gui/heart_outline.png') no-repeat;background-size:9px 9px;image-rendering:pixelated";const fill=document.createElement('img');fill.draggable=false;fill.style.cssText='position:absolute;left:1px;top:1px;width:auto;height:auto;max-width:none;image-rendering:pixelated';slot.append(fill);this.root.append(slot);this.fills.push(fill);}document.body.append(this.root);}
 public update(layout:HotbarLayout):void{if(typeof document==='undefined')return;const scale=layout.scale,left=Math.floor((innerWidth-182*scale)/2),top=innerHeight-32*scale;this.root.style.left=`${left}px`;this.root.style.top=`${top}px`;this.root.style.transformOrigin='top left';this.root.style.transform=`scale(${scale})`;const damagePhase=this.player.healthFlashTicks>0&&Math.floor(this.player.healthFlashTicks/3)%2===0,states=getHeartStates(this.player.health,this.player.recentHealth,damagePhase);for(let i=0;i<10;i++){const slot=this.root.children[i] as HTMLElement;slot.style.left=`${i*9}px`;const state=states[i]!,fill=this.fills[i]!;fill.hidden=state==='empty';if(state!=='empty')fill.src=TEXTURE[state];}}
 public dispose():void{this.root.remove?.();}}
