import type { BlockRegistry } from '../blocks/BlockRegistry';import type { ChunkManager } from '../world/ChunkManager';import type { BlockUpdateWorld } from '../world/BlockUpdateWorld';import { worldToChunkLocal } from '../world/worldToChunkCoords';import type { Player } from './Player';import type { DeathScreen } from './DeathScreen';import type { PlayerDeathController } from './PlayerDeathController';
export interface RespawnChunkLoader{dispatchCriticalLoad(chunkX:number,chunkZ:number):void;}
export class RespawnController{private pending=false;
 public constructor(private readonly player:Player,private readonly chunks:ChunkManager,private readonly streamer:RespawnChunkLoader,private readonly world:BlockUpdateWorld,private readonly blocks:BlockRegistry,private readonly spawn:Readonly<{x:number;y:number;z:number}>,private readonly screen:DeathScreen,private readonly death:PlayerDeathController,private readonly onRespawn:()=>void){}
 public request():void{if(this.pending)return;this.pending=true;this.requestSpawnArea();}
 public update():void{if(!this.pending)return;this.requestSpawnArea();const safe=this.findSafePosition();if(!safe)return;this.player.resetForRespawn(safe.x,safe.y,safe.z);this.pending=false;this.death.reset();this.screen.close();this.onRespawn();}
 private requestSpawnArea():void{const centerX=Math.floor(this.spawn.x/16),centerZ=Math.floor(this.spawn.z/16);for(let dz=-1;dz<=1;dz++)for(let dx=-1;dx<=1;dx++)if(!this.chunks.hasChunk(centerX+dx,centerZ+dz))this.streamer.dispatchCriticalLoad(centerX+dx,centerZ+dz);}
 private findSafePosition():{x:number;y:number;z:number}|undefined{const baseX=Math.floor(this.spawn.x),baseZ=Math.floor(this.spawn.z);for(let radius=0;radius<=8;radius++)for(let dz=-radius;dz<=radius;dz++)for(let dx=-radius;dx<=radius;dx++){if(radius>0&&Math.abs(dx)!==radius&&Math.abs(dz)!==radius)continue;const found=this.findSafeColumn(baseX+dx,baseZ+dz);if(found)return found;}return undefined;}
 private findSafeColumn(x:number,z:number):{x:number;y:number;z:number}|undefined{const c=worldToChunkLocal(x,z),chunk=this.chunks.getChunk(c.chunkX,c.chunkZ);if(!chunk)return undefined;const start=Math.max(1,Math.min(126,chunk.getHeight(c.localX,c.localZ)));for(let offset=0;offset<126;offset++){const y=1+((start-1+offset)%126),below=this.blocks.getById(this.world.getBlock(x,y-1,z)),feet=this.blocks.getById(this.world.getBlock(x,y,z)),head=this.blocks.getById(this.world.getBlock(x,y+1,z));if(below?.solid&&!feet?.solid&&!feet?.isLiquid&&!head?.solid&&!head?.isLiquid)return{x:x+.5,y,z:z+.5};}return undefined;}
 public get isPending():boolean{return this.pending;}}
