import * as THREE from 'three';
import { BlockIds } from '../src/blocks/BlockId.ts'; import { BlockRegistry } from '../src/blocks/BlockRegistry.ts'; import { registerDefaultBlocks } from '../src/blocks/registerDefaultBlocks.ts'; import { BlockBehaviourRegistry } from '../src/world/BlockBehaviour.ts'; import { BlockUpdateWorld } from '../src/world/BlockUpdateWorld.ts'; import { ChunkManager } from '../src/world/ChunkManager.ts'; import { LightEngine } from '../src/world/generation/lighting/LightEngine.ts';
import { EntityManager } from '../src/entities/core/EntityManager.ts'; import { createDefaultEntityTypeRegistry } from '../src/entities/core/EntityType.ts'; import { registerEntityTypes } from '../src/entities/registerEntityTypes.ts'; import { JavaRandom } from '../src/world/generation/random/JavaRandom.ts'; import { CountingParticleSink } from '../src/entities/particles/EntityParticleSink.ts'; import { CountingMobSoundSink } from '../src/entities/sound/MobSoundSink.ts'; import { DamageSource } from '../src/entities/damage/DamageSource.ts'; import { DroppedItemEntity } from '../src/entities/items/DroppedItemEntity.ts';
import { Player } from '../src/player/Player.ts'; import { PlayerModel } from '../src/player/PlayerModel.ts';
import { PigEntity } from '../src/entities/living/PigEntity.ts'; import { CowEntity } from '../src/entities/living/CowEntity.ts'; import { SheepEntity } from '../src/entities/living/SheepEntity.ts'; import { ChickenEntity } from '../src/entities/living/ChickenEntity.ts'; import { ZombieEntity } from '../src/entities/hostile/ZombieEntity.ts'; import { SkeletonEntity } from '../src/entities/hostile/SkeletonEntity.ts'; import { SpiderEntity } from '../src/entities/hostile/SpiderEntity.ts'; import { CreeperEntity } from '../src/entities/hostile/CreeperEntity.ts'; import { isMovementBackward, updateLimbAnimation, updateLivingYaw, wrapDegrees } from '../src/entities/living/LivingAnimationMath.ts';
function assert(v:boolean,m:string):void{if(!v)throw new Error(m);}const blocks=new BlockRegistry();registerDefaultBlocks(blocks);const chunks=new ChunkManager();for(let x=-1;x<=1;x++)for(let z=-1;z<=1;z++)chunks.getOrCreateChunk(x,z);const light=new LightEngine(chunks,blocks);const world=new BlockUpdateWorld(chunks,blocks,light);const behaviours=new BlockBehaviourRegistry();for(let x=-16;x<32;x++)for(let z=-16;z<32;z++)world.setBlock(x,10,z,BlockIds.Grass,{notifyNeighbours:false,updateLighting:false});
const scene=new THREE.Scene(),texture=new THREE.Texture(),material=new THREE.MeshBasicMaterial(),atlas={texture,getUvRect:()=>({u0:0,v0:0,u1:1,v1:1})} as never;const particles=new CountingParticleSink(),sounds=new CountingMobSoundSink();const player=new Player(9,11,0);const types=createDefaultEntityTypeRegistry();registerEntityTypes(types);const manager=new EntityManager({blockRegistry:blocks,behaviourRegistry:behaviours,blockUpdateWorld:world,chunkManager:chunks,scene,blockAtlas:atlas,itemAtlas:atlas,heldBlockMaterial:material,itemHeldMaterial:material,typeRegistry:types,rng:new JavaRandom(91n),particles,sounds,player,playerPosition:player.position});
const mobs=[new PigEntity(manager.context,0,11,0),new CowEntity(manager.context,2,11,0),new SheepEntity(manager.context,4,11,0),new ChickenEntity(manager.context,6,11,0),new ZombieEntity(manager.context,8,11,0),new SkeletonEntity(manager.context,10,11,0),new SpiderEntity(manager.context,12,11,0),new CreeperEntity(manager.context,14,11,0)];
const expected=[[.9,.9],[.9,1.3],[.9,1.3],[.3,.4],[.6,1.8],[.6,1.8],[1.4,.9],[.6,1.8]];mobs.forEach((mob,i)=>{assert(mob.width===expected[i]![0]&&mob.height===expected[i]![1],`${mob.typeStringId} collision dimensions`);assert(Math.abs(mob.getEyeHeight()-mob.height*.85)<1e-9,`${mob.typeStringId} eye height`);});
const playerModel=new PlayerModel();playerModel.root.updateMatrixWorld(true);const playerBaseBox=new THREE.Box3();for(const group of [playerModel.headGroup,playerModel.bodyGroup,playerModel.leftArmGroup,playerModel.rightArmGroup,playerModel.leftLegGroup,playerModel.rightLegGroup])playerBaseBox.expandByObject(group.children[0]!);const playerBaseSize=new THREE.Vector3();playerBaseBox.getSize(playerBaseSize);
for(const mob of [mobs[4]!,mobs[5]!]){mob.renderObject!.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(mob.renderObject!);const size=new THREE.Vector3();box.getSize(size);assert(Math.abs(size.y-playerBaseSize.y)<.02,`${mob.typeStringId} visual height matches Player base body`);assert(Math.abs(size.y-2)<.02,`${mob.typeStringId} uses verified 32px/2-block biped extent`);assert(Math.abs(box.min.y)<.001,`${mob.typeStringId} feet align to ground origin`);assert(Math.abs(mob.renderObject!.scale.x-mob.renderObject!.scale.y)<1e-9&&Math.abs(mob.renderObject!.scale.y-mob.renderObject!.scale.z)<1e-9,`${mob.typeStringId} root scale remains uniform`);}assert(Math.abs(playerBaseBox.min.y)<.001,'Player base feet align to ground origin');
const turn=updateLivingYaw(0,0,200,false);assert(Math.abs(wrapDegrees(turn.headYaw-turn.bodyYaw))<=75,'head yaw clamps to ±75');assert(Math.abs(turn.bodyYaw)>0,'body follows look beyond clamp');assert(isMovementBackward(0,-1,0)&&!isMovementBackward(0,1,0),'backwards gait derives from travel/body dot product');const idle=updateLimbAnimation(0,1,false);assert(idle.amount<1&&idle.phaseDelta===0,'stationary walk cycle decays without phase advance');
const directions=[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]] as const;for(const [dx,dz] of directions){const movementYaw=Math.atan2(dz,dx)*180/Math.PI-90;let body=0;for(let tick=0;tick<20;tick++)body=updateLivingYaw(body,movementYaw,movementYaw,true).bodyYaw;assert(Math.abs(wrapDegrees(body-movementYaw))<=5,'body settles within 5° of all compass/diagonal travel');for(let i=0;i<mobs.length;i++){const mob=mobs[i]!;mob.setPosition(i%2===0?-8-i:8+i,11,i%2===0?-8:8);mob.prevRenderYawOffset=body;mob.renderYawOffset=body;mob.prevHeadYaw=body;mob.headYaw=body;mob.updateRenderInterpolation(1);const forward=new THREE.Vector3(0,0,1).applyQuaternion(mob.renderObject!.quaternion).normalize();const move=new THREE.Vector3(dx,0,dz).normalize();assert(forward.dot(move)>Math.cos(5*Math.PI/180),`${mob.typeStringId} local +Z faces travel without 90°/180° error`);}}
const pig=mobs[0]!;manager.add(pig);manager.tick();pig.attackEntityFrom(DamageSource.generic(),1);assert(sounds.count('mob.pig')===1,'hurt emits exactly one Pig event');assert(particles.deathCount===0,'ordinary damage emits no particles');pig.hurtResistantTime=0;pig.attackEntityFrom(DamageSource.generic(),99);assert(sounds.count('mob.pigdeath')===1,'death sound emits once');assert(particles.deathCount===0,'death particles are delayed');for(let i=0;i<20;i++)manager.tick();assert(particles.deathCount===1,'terminal death emits particles exactly once');for(let i=0;i<5;i++)manager.tick();assert(particles.deathCount===1,'death particles never replay');
const ambientPig=new PigEntity(manager.context,1,11,2);manager.add(ambientPig);manager.tick();for(let i=0;i<3000&&!sounds.events.some(e=>e.kind==='ambient');i++)manager.tick();assert(sounds.events.some(e=>e.kind==='ambient'&&e.id==='mob.pig'),'Beta ambient counter dispatches positioned Pig event');const positioned=sounds.events.find(e=>e.kind==='ambient')!;assert(positioned.attenuationDistance===16&&positioned.pitch>=0.8&&positioned.pitch<=1.2,'sound event carries attenuation and pitch metadata');
const cow=new CowEntity(manager.context,1,11,1);manager.add(cow);manager.tick();cow.attackEntityFrom(DamageSource.generic(),99);manager.tick();const drops=manager.getEntitiesInChunk(0,0).filter((e):e is DroppedItemEntity=>e instanceof DroppedItemEntity);assert(!drops.some(d=>d.drop.id==='beef_raw'||d.drop.id==='chicken_raw'),'post-Beta meat drops removed');for(const drop of drops)assert(drop.drop.count>=1&&drop.drop.count<=2,'base Beta drop stacks are at most two');
const dropCases:[()=>PigEntity|CowEntity|SheepEntity|ChickenEntity|ZombieEntity|SkeletonEntity|SpiderEntity|CreeperEntity,readonly string[]][]=[
  [()=>{const e=new PigEntity(manager.context,2,11,2);e.setOnFire(20);return e;},['porkchop_cooked']],
  [()=>new CowEntity(manager.context,3,11,2),['leather']], [()=>new SheepEntity(manager.context,4,11,2),[String(BlockIds.Wool)]],
  [()=>new ChickenEntity(manager.context,5,11,2),['feather']], [()=>new ZombieEntity(manager.context,6,11,2),['feather']],
  [()=>new SkeletonEntity(manager.context,7,11,2),['arrow','bone']], [()=>new SpiderEntity(manager.context,8,11,2),['string']],
  [()=>new CreeperEntity(manager.context,9,11,2),['gunpowder']],
];
for(const [create,allowed] of dropCases){const before=new Set(manager.getEntitiesInChunk(0,0).filter((e):e is DroppedItemEntity=>e instanceof DroppedItemEntity));const entity=create();entity.attackEntityFrom(DamageSource.generic(),99);manager.tick();const added=manager.getEntitiesInChunk(0,0).filter((e):e is DroppedItemEntity=>e instanceof DroppedItemEntity&&!before.has(e));for(const drop of added){assert(allowed.includes(String(drop.drop.id)),`${entity.typeStringId} emits only strict Beta drop IDs`);assert(drop.drop.count>=1&&drop.drop.count<=2,`${entity.typeStringId} Beta stack count is at most two`);}entity.onRemove();}
const lamb=new SheepEntity(manager.context,10,11,2);lamb.setGrowingAge(-100);const beforeBaby=manager.getEntitiesInChunk(0,0).filter(e=>e instanceof DroppedItemEntity).length;lamb.attackEntityFrom(DamageSource.generic(),99);manager.tick();assert(manager.getEntitiesInChunk(0,0).filter(e=>e instanceof DroppedItemEntity).length===beforeBaby,'babies produce no adult drops');lamb.onRemove();
const skeleton=mobs[5] as SkeletonEntity;skeleton.target=player;skeleton.attackTime=0;assert(skeleton.shootTarget()&&sounds.count('random.bow')===1,'Skeleton bow emits once');const creeper=mobs[7] as CreeperEntity;player.position.x=creeper.position.x-1;player.position.z=creeper.position.z;creeper.target=player;creeper.fuseTicks=0;creeper.updateFuse();assert(sounds.count('random.fuse')===1,'Creeper fuse emits once on ignition');creeper.updateFuse();assert(sounds.count('random.fuse')===1,'Creeper fuse sound does not duplicate');
for(const mob of mobs)if(!mob.removed)mob.onRemove();manager.dispose();material.dispose();texture.dispose();console.log('Mob dimensions, animation, drops, sounds and death parity validation passed.');
