import * as THREE from 'three';
import { BlockIds } from '../src/blocks/BlockId.ts'; import { BlockRegistry } from '../src/blocks/BlockRegistry.ts'; import { registerDefaultBlocks } from '../src/blocks/registerDefaultBlocks.ts';
import { EntityManager } from '../src/entities/core/EntityManager.ts'; import { createDefaultEntityTypeRegistry } from '../src/entities/core/EntityType.ts'; import { registerEntityTypes } from '../src/entities/registerEntityTypes.ts';
import { NaturalMobSpawner, HOSTILE_CREATURE_CAP, isHostileSpawningEnabled, scaledHostileCap, selectWeightedHostileSpawn } from '../src/entities/spawning/NaturalMobSpawner.ts';
import { SpiderEntity } from '../src/entities/hostile/SpiderEntity.ts'; import { HostileEntity } from '../src/entities/hostile/HostileEntity.ts';
import { Player } from '../src/player/Player.ts'; import { BlockBehaviourRegistry } from '../src/world/BlockBehaviour.ts'; import { BlockUpdateWorld } from '../src/world/BlockUpdateWorld.ts'; import { ChunkManager } from '../src/world/ChunkManager.ts'; import { Difficulty } from '../src/world/Difficulty.ts'; import { ClimateSampler } from '../src/world/generation/climate/ClimateSampler.ts'; import { BETA_HOSTILE_SPAWNS, BIOMES } from '../src/world/generation/climate/biomes.ts'; import { LightEngine } from '../src/world/generation/lighting/LightEngine.ts'; import { JavaRandom } from '../src/world/generation/random/JavaRandom.ts';
function assert(v:boolean,m:string):void{if(!v)throw new Error(m);}
assert(HOSTILE_CREATURE_CAP===70,'Beta monster cap is 70');assert(scaledHostileCap(256)===70&&scaledHostileCap(289)===79,'hostile cap uses floor(70*n/256)');
assert(BETA_HOSTILE_SPAWNS.map(e=>`${e.kind}:${e.weight}`).join(',')==='spider:10,zombie:10,skeleton:10,creeper:10','supported Beta monster entries have weight 10');
for(const biome of Object.values(BIOMES))assert(biome.hostileSpawns===BETA_HOSTILE_SPAWNS,`${biome.id} shares authoritative monster list`);
assert(selectWeightedHostileSpawn(BETA_HOSTILE_SPAWNS,()=>0).kind==='spider'&&selectWeightedHostileSpawn(BETA_HOSTILE_SPAWNS,()=>10).kind==='zombie'&&selectWeightedHostileSpawn(BETA_HOSTILE_SPAWNS,()=>39).kind==='creeper','weighted boundaries deterministic');
assert(!isHostileSpawningEnabled(Difficulty.Peaceful)&&isHostileSpawningEnabled(Difficulty.Easy)&&isHostileSpawningEnabled(Difficulty.Normal)&&isHostileSpawningEnabled(Difficulty.Hard),'only Peaceful disables hostile spawning');
const blocks=new BlockRegistry();registerDefaultBlocks(blocks);const chunks=new ChunkManager();const chunk=chunks.getOrCreateChunk(0,0);const light=new LightEngine(chunks,blocks);const world=new BlockUpdateWorld(chunks,blocks,light);const behaviours=new BlockBehaviourRegistry();
for(let x=0;x<16;x++)for(let z=0;z<16;z++){world.setBlock(x,10,z,BlockIds.Stone,{notifyNeighbours:false,updateLighting:false});chunk.setSkylight(x,11,z,0);chunk.setBlocklight(x,11,z,0);}
const scene=new THREE.Scene(),texture=new THREE.Texture(),material=new THREE.MeshBasicMaterial(),atlas={texture,getUvRect:()=>({u0:0,v0:0,u1:1,v1:1})} as never;const types=createDefaultEntityTypeRegistry();registerEntityTypes(types);const player=new Player(100,11,0);const manager=new EntityManager({blockRegistry:blocks,behaviourRegistry:behaviours,blockUpdateWorld:world,chunkManager:chunks,scene,blockAtlas:atlas,itemAtlas:atlas,heldBlockMaterial:material,itemHeldMaterial:material,typeRegistry:types,rng:new JavaRandom(1n),player,playerPosition:player.position,difficulty:()=>Difficulty.Normal,isDaytime:()=>false,skylightSubtracted:()=>15});
const scripted={nextInt(bound:number):number{if(bound===16)return 8;if(bound===128)return 11;return 0;},nextFloat():number{return 0.25;}} as JavaRandom;
const spawner=new NaturalMobSpawner({chunkManager:chunks,entityManager:manager,blockRegistry:blocks,behaviourRegistry:behaviours,world,climateSampler:new ClimateSampler(1n),rng:scripted,player,worldSpawn:{x:-100,y:11,z:0},getSkylightSubtracted:()=>15,getDifficulty:()=>Difficulty.Normal,isThundering:()=>false});
const result=spawner.tick();assert(spawner.getEligibleChunkCount()===289&&spawner.getScaledHostileCap()===79,'full eligible set scales cap while loaded intersection receives attempts');assert(result.hostile===1&&result.passive===0,'hostile pass runs before passive and spawns on valid dark terrain');manager.tick();assert(manager.activeHostileMobCount===1,'active loaded hostile count maintained without projectiles');const active=manager.getEntitiesInChunk(0,0);assert(active.length===1&&active[0] instanceof SpiderEntity,'weighted natural spawn uses normal EntityManager pipeline');const tag=active[0]!.writeToNbt();assert(tag.value.get('id')?.value==='Spider','natural hostile persists with owning chunk');chunks.removeChunk(0,0);assert(manager.activeHostileMobCount===0&&manager.parkedCount===1,'unload removes hostile from active cap');chunks.getOrCreateChunk(0,0);assert(manager.activeHostileMobCount===1&&manager.getEntitiesInChunk(0,0)[0] instanceof HostileEntity,'reload restores one hostile and cap membership');manager.loadChunkEntities([tag]);manager.tick();assert(manager.activeHostileMobCount===1,'duplicate UUID load does not duplicate hostile');chunks.removeChunk(0,0);assert(spawner.tick().hostile===0&&!chunks.hasChunk(0,0),'spawner never loads or generates absent chunks');
manager.dispose();material.dispose();texture.dispose();console.log('Natural hostile spawning validation passed.');
