import { DEFAULT_ITEM_DEFINITIONS,type ItemDefinitionRegistry } from '../items/ItemDefinitionRegistry';
export interface ItemIdentity{readonly id:number|string;readonly type:'block'|'item';}export type ItemDamageResult={readonly status:'ignored'|'damaged'|'broken';readonly previousDamage:number;readonly damage:number;readonly maxDurability:number};
export class ItemStack{public readonly identity:ItemIdentity;public count:number;public metadata:number;public damage:number;
 public constructor(id:number|string,type:'block'|'item',count:number,metadata=0,damage=0,definitions:ItemDefinitionRegistry=DEFAULT_ITEM_DEFINITIONS){this.identity={id,type};this.count=count;this.metadata=metadata;const max=type==='item'?definitions.get(id)?.durability:undefined;this.damage=max!==undefined?Math.max(0,Math.min(max-1,Math.floor(damage))):0;}
 public clone():ItemStack{return new ItemStack(this.identity.id,this.identity.type,this.count,this.metadata,this.damage);}
 public matches(other:ItemStack):boolean{return this.identity.id===other.identity.id&&this.identity.type===other.identity.type&&this.metadata===other.metadata&&this.damage===other.damage;}
 public getDefinition(definitions:ItemDefinitionRegistry=DEFAULT_ITEM_DEFINITIONS){return this.identity.type==='item'?definitions.get(this.identity.id):undefined;}
 public getMaxDurability(definitions:ItemDefinitionRegistry=DEFAULT_ITEM_DEFINITIONS):number{return this.getDefinition(definitions)?.durability??0;}
 public isDamageable(definitions:ItemDefinitionRegistry=DEFAULT_ITEM_DEFINITIONS):boolean{return this.getMaxDurability(definitions)>0;}
 public getRemainingDurability(definitions:ItemDefinitionRegistry=DEFAULT_ITEM_DEFINITIONS):number{const max=this.getMaxDurability(definitions);return max>0?Math.max(0,max-this.damage):0;}
 public getDurabilityFraction(definitions:ItemDefinitionRegistry=DEFAULT_ITEM_DEFINITIONS):number{const max=this.getMaxDurability(definitions);return max>0?Math.max(0,Math.min(1,(max-this.damage)/max)):1;}
 public damageItem(amount:number,definitions:ItemDefinitionRegistry=DEFAULT_ITEM_DEFINITIONS):ItemDamageResult{const max=this.getMaxDurability(definitions),previous=this.damage;if(max<=0||amount<=0){this.damage=0;return{status:'ignored',previousDamage:previous,damage:0,maxDurability:max};}const next=Math.max(0,previous+Math.floor(amount));this.damage=Math.min(max,next);return{status:next>=max?'broken':'damaged',previousDamage:previous,damage:this.damage,maxDurability:max};}}
export function getMaxStackSize(identity:ItemIdentity):number{if(identity.type==='block')return 64;const definition=DEFAULT_ITEM_DEFINITIONS.get(identity.id);if(definition)return definition.stackSize;const name=String(identity.id);if(name.includes('sign')||name==='reeds')return 16;if(name.includes('helmet')||name.includes('chestplate')||name.includes('leggings')||name.includes('boots')||name==='flint_and_steel'||name.startsWith('bucket_'))return 1;return 64;}
